version: '3.4'

services:
  utn-prog-ii:
    container_name: utn-prog2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - todolist.db:/app/db

volumes:
  todolist.db:
